services:
  backend:
    build:
      context: ./api
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SITEOWNER_USERNAME=${SITEOWNER_USERNAME}
      - SITEOWNER_PASSWORD=${SITEOWNER_PASSWORD}
      - API_JWT_SECRET=${API_JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - UPLOADTHING_TOKEN=${UPLOADTHING_TOKEN}
      - NODE_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./app
      target: development
    ports:
      - '5173:5173'
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
